# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cppls_cpp <- function(matrix_X, Y, Y_add, ncomp, center, stripped, transpose, w_tol, X_tol) {
    .Call(`_scSLIDE_cppls_cpp`, matrix_X, Y, Y_add, ncomp, center, stripped, transpose, w_tol, X_tol)
}

kernelpls_cpp <- function(matrix_X, Y, ncomp, center, stripped, transpose) {
    .Call(`_scSLIDE_kernelpls_cpp`, matrix_X, Y, ncomp, center, stripped, transpose)
}

